### PR TITLE
Update jquery.serialize-object.js

### PR DESCRIPTION
**Pull request by mage3k**
use lodash rePropName: /[^.[\]]+|\[(?:(-?\d+(?:\.\d+)?)|(["'])((?:(?!\2)[^\n\\]|\\.)*?)\2)\]/g

fix addPair return

### CODE REVIEW

**Comment by macek** [comment]
Not sure what you're trying to do here

The regexp you've provided doesn't "fix" anything as far as I can tell. What I can see is that it breaks several tests. The following tests fail with your PR

* should merge a push array field
* should merge multiple fixed fields
* should punish user for mixing pushed array and fixed array fields
* should accept an array of pairs
* checkbox inputs as booleans if no value is present
* checkbox inputs as booleans if value is 'on'
* seriazlie a single form
* serialize multiple forms
* serialize a selection of inputs

Also, the "fix addPair return" is not broken.

```js
// original code
if (!patterns.validate.test(pair.name)) return this;

// your code
if (!(patterns.validate.test(pair.name))) return this;
```

The extra parentheses are meaningless here

**Comment by mage3k** [comment]
Sorry, I just edit this file online without test

When I use serializeObject, some fields name was skiped in 

    if (!patterns.validate.test(pair.name)) return this

like `a[1].b.a_c` 

I think `set` method in lodash can serialize `a[1].b.a_c` string, so I replaced `patterns.validate`

But I have new problem. when the path string is simple string like 'a_b_c', the 

    `!patterns.validate.test(pair.name)`

always return false, so I add brackets

Sorry ...

**Comment by macek** [comment]
If you read the README, you'd see specific usage of "dot notation"

By default, the plugin supports inputs named like

```html
<input name="a[1][b][a_c]">
```

**Comment by mage3k** [comment]
Thx~

Maybe next time I will check more careful.

**Pull request closed without merging**
